# Generated by Django 4.1.3 on 2022-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('network', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=300)),
                ('ram', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.CharField(max_length=200)),
            ],
        ),
    ]
