# Generated by Django 4.1.3 on 2022-12-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0002_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
