# Generated by Django 4.1.3 on 2022-12-08 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phone_app', '0004_alter_mobile_description_alter_mobile_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(max_length=10)),
                ('pincode', models.IntegerField(null=True)),
                ('country', models.TextField(max_length=10, null=True)),
                ('flat', models.TextField(max_length=100, null=True)),
                ('area', models.TextField(max_length=150, null=True)),
                ('landmark', models.TextField(max_length=100, null=True)),
                ('state', models.TextField(max_length=50, null=True)),
                ('city', models.TextField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
