# Generated by Django 4.1.3 on 2022-12-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
