# Generated by Django 4.1.3 on 2022-12-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0007_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
