# Generated by Django 4.1.3 on 2022-12-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0008_rename_product_id_cart_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
