# Generated by Django 4.1.3 on 2022-12-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0014_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
