# Generated by Django 4.1.3 on 2022-12-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0015_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.TextField(),
        ),
    ]
