# Generated by Django 4.1.3 on 2022-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0020_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.TextField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.TextField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='flat',
            field=models.TextField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='landmark',
            field=models.TextField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.TextField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.TextField(default='', max_length=50, null=True),
        ),
    ]
