# Generated by Django 4.1.3 on 2022-12-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0022_alter_profile_area_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
